// <auto-generated />
using System;
using HealthSync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthSync.Infrastructure.Migrations
{
    [DbContext(typeof(HealthSyncDbContext))]
    [Migration("20251204205725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthSync.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            Description = "Classic bodyweight chest exercise",
                            Difficulty = "Beginner",
                            Equipment = "None",
                            MuscleGroup = "Chest",
                            Name = "Push-ups"
                        },
                        new
                        {
                            ExerciseId = 2,
                            Description = "Compound chest exercise with barbell",
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            MuscleGroup = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            ExerciseId = 3,
                            Description = "Isolation exercise for chest",
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            MuscleGroup = "Chest",
                            Name = "Dumbbell Fly"
                        },
                        new
                        {
                            ExerciseId = 4,
                            Description = "Bodyweight back exercise",
                            Difficulty = "Intermediate",
                            Equipment = "Pull-up Bar",
                            MuscleGroup = "Back",
                            Name = "Pull-ups"
                        },
                        new
                        {
                            ExerciseId = 5,
                            Description = "Compound full-body exercise",
                            Difficulty = "Advanced",
                            Equipment = "Barbell",
                            MuscleGroup = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            ExerciseId = 6,
                            Description = "Compound back exercise",
                            Difficulty = "Intermediate",
                            Equipment = "Barbell",
                            MuscleGroup = "Back",
                            Name = "Bent-over Row"
                        },
                        new
                        {
                            ExerciseId = 7,
                            Description = "Fundamental leg exercise",
                            Difficulty = "Beginner",
                            Equipment = "None",
                            MuscleGroup = "Legs",
                            Name = "Squats"
                        },
                        new
                        {
                            ExerciseId = 8,
                            Description = "Unilateral leg exercise",
                            Difficulty = "Beginner",
                            Equipment = "None",
                            MuscleGroup = "Legs",
                            Name = "Lunges"
                        },
                        new
                        {
                            ExerciseId = 9,
                            Description = "Machine-based leg exercise",
                            Difficulty = "Intermediate",
                            Equipment = "Machine",
                            MuscleGroup = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            ExerciseId = 10,
                            Description = "Overhead pressing movement",
                            Difficulty = "Intermediate",
                            Equipment = "Dumbbells",
                            MuscleGroup = "Shoulders",
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            ExerciseId = 11,
                            Description = "Isolation shoulder exercise",
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            MuscleGroup = "Shoulders",
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            ExerciseId = 12,
                            Description = "Isolation bicep exercise",
                            Difficulty = "Beginner",
                            Equipment = "Dumbbells",
                            MuscleGroup = "Arms",
                            Name = "Bicep Curls"
                        },
                        new
                        {
                            ExerciseId = 13,
                            Description = "Bodyweight tricep exercise",
                            Difficulty = "Intermediate",
                            Equipment = "Parallel Bars",
                            MuscleGroup = "Arms",
                            Name = "Tricep Dips"
                        },
                        new
                        {
                            ExerciseId = 14,
                            Description = "Isometric core exercise",
                            Difficulty = "Beginner",
                            Equipment = "None",
                            MuscleGroup = "Core",
                            Name = "Plank"
                        },
                        new
                        {
                            ExerciseId = 15,
                            Description = "Basic abdominal exercise",
                            Difficulty = "Beginner",
                            Equipment = "None",
                            MuscleGroup = "Core",
                            Name = "Crunches"
                        });
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.ExerciseSession", b =>
                {
                    b.Property<int>("ExerciseSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseSessionId"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("RestSec")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseSessionId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("ExerciseSessions");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.FoodEntry", b =>
                {
                    b.Property<int>("FoodEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodEntryId"));

                    b.Property<decimal?>("CaloriesKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("CarbsG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("FatG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NutritionLogId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProteinG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("FoodEntryId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("NutritionLogId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemId"));

                    b.Property<decimal>("CaloriesKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ServingSize")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodItemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            CaloriesKcal = 165m,
                            CarbsG = 0m,
                            FatG = 3.6m,
                            Name = "Chicken Breast",
                            ProteinG = 31m,
                            ServingSize = 100m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 2,
                            CaloriesKcal = 111m,
                            CarbsG = 23m,
                            FatG = 0.9m,
                            Name = "Brown Rice",
                            ProteinG = 2.6m,
                            ServingSize = 100m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 3,
                            CaloriesKcal = 105m,
                            CarbsG = 27m,
                            FatG = 0.4m,
                            Name = "Banana",
                            ProteinG = 1.3m,
                            ServingSize = 118m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 4,
                            CaloriesKcal = 100m,
                            CarbsG = 6m,
                            FatG = 0m,
                            Name = "Greek Yogurt",
                            ProteinG = 17m,
                            ServingSize = 170m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 5,
                            CaloriesKcal = 7m,
                            CarbsG = 1.1m,
                            FatG = 0.1m,
                            Name = "Spinach",
                            ProteinG = 0.9m,
                            ServingSize = 30m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 6,
                            CaloriesKcal = 208m,
                            CarbsG = 0m,
                            FatG = 13m,
                            Name = "Salmon",
                            ProteinG = 20m,
                            ServingSize = 100m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 7,
                            CaloriesKcal = 112m,
                            CarbsG = 26m,
                            FatG = 0.1m,
                            Name = "Sweet Potato",
                            ProteinG = 2.1m,
                            ServingSize = 130m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 8,
                            CaloriesKcal = 72m,
                            CarbsG = 0.4m,
                            FatG = 4.8m,
                            Name = "Eggs",
                            ProteinG = 6.3m,
                            ServingSize = 50m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 9,
                            CaloriesKcal = 150m,
                            CarbsG = 27m,
                            FatG = 2.8m,
                            Name = "Oatmeal",
                            ProteinG = 5.3m,
                            ServingSize = 40m,
                            ServingUnit = "g"
                        },
                        new
                        {
                            FoodItemId = 10,
                            CaloriesKcal = 31m,
                            CarbsG = 6m,
                            FatG = 0.3m,
                            Name = "Broccoli",
                            ProteinG = 2.5m,
                            ServingSize = 91m,
                            ServingUnit = "g"
                        });
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetValue")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GoalId");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.NutritionLog", b =>
                {
                    b.Property<int>("NutritionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionLogId"));

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NutritionLogId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionLogs");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "User",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(508),
                            Description = "Xem danh sách người dùng",
                            PermissionCode = "USER_READ"
                        },
                        new
                        {
                            Id = 102,
                            Category = "User",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(511),
                            Description = "Khóa tài khoản người dùng",
                            PermissionCode = "USER_BAN"
                        },
                        new
                        {
                            Id = 103,
                            Category = "User",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(512),
                            Description = "Cập nhật vai trò người dùng",
                            PermissionCode = "USER_UPDATE_ROLE"
                        },
                        new
                        {
                            Id = 104,
                            Category = "User",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(512),
                            Description = "Xóa người dùng",
                            PermissionCode = "USER_DELETE"
                        },
                        new
                        {
                            Id = 201,
                            Category = "Exercise",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(513),
                            Description = "Xem thư viện bài tập",
                            PermissionCode = "EXERCISE_READ"
                        },
                        new
                        {
                            Id = 202,
                            Category = "Exercise",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(514),
                            Description = "Thêm bài tập mới",
                            PermissionCode = "EXERCISE_CREATE"
                        },
                        new
                        {
                            Id = 203,
                            Category = "Exercise",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(515),
                            Description = "Cập nhật bài tập",
                            PermissionCode = "EXERCISE_UPDATE"
                        },
                        new
                        {
                            Id = 204,
                            Category = "Exercise",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(516),
                            Description = "Xóa bài tập",
                            PermissionCode = "EXERCISE_DELETE"
                        },
                        new
                        {
                            Id = 301,
                            Category = "Food",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(517),
                            Description = "Xem thư viện thực phẩm",
                            PermissionCode = "FOOD_READ"
                        },
                        new
                        {
                            Id = 302,
                            Category = "Food",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(518),
                            Description = "Thêm thực phẩm mới",
                            PermissionCode = "FOOD_CREATE"
                        },
                        new
                        {
                            Id = 303,
                            Category = "Food",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(519),
                            Description = "Cập nhật thực phẩm",
                            PermissionCode = "FOOD_UPDATE"
                        },
                        new
                        {
                            Id = 304,
                            Category = "Food",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(519),
                            Description = "Xóa thực phẩm",
                            PermissionCode = "FOOD_DELETE"
                        },
                        new
                        {
                            Id = 401,
                            Category = "WorkoutLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(520),
                            Description = "Xem nhật ký tập luyện",
                            PermissionCode = "WORKOUT_LOG_READ"
                        },
                        new
                        {
                            Id = 402,
                            Category = "WorkoutLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(522),
                            Description = "Tạo nhật ký tập luyện",
                            PermissionCode = "WORKOUT_LOG_CREATE"
                        },
                        new
                        {
                            Id = 403,
                            Category = "WorkoutLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(523),
                            Description = "Cập nhật nhật ký tập luyện",
                            PermissionCode = "WORKOUT_LOG_UPDATE"
                        },
                        new
                        {
                            Id = 404,
                            Category = "WorkoutLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(524),
                            Description = "Xóa nhật ký tập luyện",
                            PermissionCode = "WORKOUT_LOG_DELETE"
                        },
                        new
                        {
                            Id = 501,
                            Category = "NutritionLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(525),
                            Description = "Xem nhật ký dinh dưỡng",
                            PermissionCode = "NUTRITION_LOG_READ"
                        },
                        new
                        {
                            Id = 502,
                            Category = "NutritionLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(526),
                            Description = "Tạo nhật ký dinh dưỡng",
                            PermissionCode = "NUTRITION_LOG_CREATE"
                        },
                        new
                        {
                            Id = 503,
                            Category = "NutritionLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(527),
                            Description = "Cập nhật nhật ký dinh dưỡng",
                            PermissionCode = "NUTRITION_LOG_UPDATE"
                        },
                        new
                        {
                            Id = 504,
                            Category = "NutritionLog",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(528),
                            Description = "Xóa nhật ký dinh dưỡng",
                            PermissionCode = "NUTRITION_LOG_DELETE"
                        },
                        new
                        {
                            Id = 601,
                            Category = "Goal",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(528),
                            Description = "Xem mục tiêu",
                            PermissionCode = "GOAL_READ"
                        },
                        new
                        {
                            Id = 602,
                            Category = "Goal",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(529),
                            Description = "Tạo mục tiêu",
                            PermissionCode = "GOAL_CREATE"
                        },
                        new
                        {
                            Id = 603,
                            Category = "Goal",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(530),
                            Description = "Cập nhật mục tiêu",
                            PermissionCode = "GOAL_UPDATE"
                        },
                        new
                        {
                            Id = 604,
                            Category = "Goal",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(531),
                            Description = "Xóa mục tiêu",
                            PermissionCode = "GOAL_DELETE"
                        },
                        new
                        {
                            Id = 701,
                            Category = "Dashboard",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(532),
                            Description = "Xem dashboard cá nhân",
                            PermissionCode = "DASHBOARD_VIEW"
                        },
                        new
                        {
                            Id = 702,
                            Category = "Dashboard",
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(532),
                            Description = "Xem dashboard admin",
                            PermissionCode = "DASHBOARD_ADMIN"
                        });
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.ProgressRecord", b =>
                {
                    b.Property<int>("ProgressRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressRecordId"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("WaistCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProgressRecordId");

                    b.HasIndex("GoalId");

                    b.ToTable("ProgressRecords");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(475),
                            Description = "Quản trị viên hệ thống, có toàn quyền",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(486),
                            Description = "Người dùng cuối sử dụng app",
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 101,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(570)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 102,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(571)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 103,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(572)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 104,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(572)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 201,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(573)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 202,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(574)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 203,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(574)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 204,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(575)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 301,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(576)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 302,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(576)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 303,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(577)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 304,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(578)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 401,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(578)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 402,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(579)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 403,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(579)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 404,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(580)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 501,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(580)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 502,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(581)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 503,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(582)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 504,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(582)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 601,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(584)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 602,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(585)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 603,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(585)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 604,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(586)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 701,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(620)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 702,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(621)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 201,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(621)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 301,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(622)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 401,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(623)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 402,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(623)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 403,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(624)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 404,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(624)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 501,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(625)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 502,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(626)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 503,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(626)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 504,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(627)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 601,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(628)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 602,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(628)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 603,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(629)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 604,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(629)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 701,
                            GrantedAt = new DateTime(2025, 12, 4, 20, 57, 24, 775, DateTimeKind.Utc).AddTicks(630)
                        });
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<int>("WorkoutLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutLogId"));

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkoutLogId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.ExerciseSession", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.Exercise", "Exercise")
                        .WithMany("ExerciseSessions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthSync.Domain.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("ExerciseSessions")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.FoodEntry", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany("FoodEntries")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthSync.Domain.Entities.NutritionLog", "NutritionLog")
                        .WithMany("FoodEntries")
                        .HasForeignKey("NutritionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("NutritionLog");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Goal", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.NutritionLog", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.ApplicationUser", "User")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.ProgressRecord", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.Goal", "Goal")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthSync.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("HealthSync.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthSync.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("HealthSync.Domain.Entities.ApplicationUser", "User")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("NutritionLogs");

                    b.Navigation("Profile");

                    b.Navigation("UserRoles");

                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("ExerciseSessions");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.FoodItem", b =>
                {
                    b.Navigation("FoodEntries");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Goal", b =>
                {
                    b.Navigation("ProgressRecords");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.NutritionLog", b =>
                {
                    b.Navigation("FoodEntries");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HealthSync.Domain.Entities.WorkoutLog", b =>
                {
                    b.Navigation("ExerciseSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
